function Strings( config ) {

	const language = config.getKey( 'language' );

	const values = {

		en: {

			'prompt/file/open': 'Any unsaved data will be lost. Are you sure?',
			'prompt/file/failedToOpenProject': 'Failed to open project!',
			'prompt/file/export/noMeshSelected': 'No Mesh selected!',
			'prompt/file/export/noObjectSelected': 'No Object selected!',
			'prompt/script/remove': 'Are you sure?',
			'prompt/history/clear': 'The Undo/Redo History will be cleared. Are you sure?',
			'prompt/history/preserve': 'The history will be preserved across sessions.\nThis can have an impact on performance when working with textures.',
			'prompt/history/forbid': 'Undo/Redo disabled while scene is playing.',
			'prompt/rendering/realistic/unsupportedMaterial': 'REALISTIC Shading: Only MeshStandardMaterial and MeshPhysicalMaterial are supported',

			'command/AddObject': 'Add Object',
			'command/AddScript': 'Add Script',
			'command/MoveObject': 'Move Object',
			'command/MultiCmds': 'Multiple Changes',
			'command/RemoveObject': 'Remove Object',
			'command/RemoveScript': 'Remove Script',
			'command/SetColor': 'Set Color',
			'command/SetGeometry': 'Set Geometry',
			'command/SetGeometryValue': 'Set Geometry Value',
			'command/SetMaterialColor': 'Set Material Color',
			'command/SetMaterial': 'Set Material',
			'command/SetMaterialMap': 'Set Material Map',
			'command/SetMaterialRange': 'Set Material Range',
			'command/SetMaterialValue': 'Set Material Value',
			'command/SetMaterialVector': 'Set Material Vector',
			'command/SetPosition': 'Set Position',
			'command/SetRotation': 'Set Rotation',
			'command/SetScale': 'Set Scale',
			'command/SetScene': 'Set Scene',
			'command/SetScriptValue': 'Set Script Value',
			'command/SetShadowValue': 'Set Shadow Value',
			'command/SetUuid': 'Set UUID',
			'command/SetValue': 'Set Value',

			'menubar/file': 'File',
			'menubar/file/new': 'New',
			'menubar/file/new/empty': 'Empty',
			'menubar/file/new/Arkanoid': 'Arkanoid',
			'menubar/file/new/Camera': 'Camera',
			'menubar/file/new/Custom': 'New File',
			'menubar/file/new/Particles': 'Particles',
			'menubar/file/new/Pong': 'Pong',
			'menubar/file/new/Shaders': 'Shaders',
			'menubar/file/open': 'Open',
			'menubar/file/save': 'Save',
			'menubar/file/import': 'Import',
			'menubar/file/export': 'Export',

			'menubar/edit': 'Edit',
			'menubar/edit/undo': 'Undo',
			'menubar/edit/redo': 'Redo',
			'menubar/edit/center': 'Center',
			'menubar/edit/clone': 'Clone',
			'menubar/edit/delete': 'Delete',

			'menubar/add': 'Add',
			'menubar/add/group': 'Group',

			// 'menubar/add/mesh': 'Mesh',
			'menubar/add/mesh/plane': 'Plane',
			'menubar/add/box': 'Platform',
			'menubar/add/end': 'Ending',
			// 'menubar/add/mesh/circle': 'Circle',
			'menubar/add/cylinder': 'Cylinder',
			// 'menubar/add/mesh/ring': 'Ring',
			'menubar/add/sphere': 'Sphere',
			// 'menubar/add/mesh/dodecahedron': 'Dodecahedron',
			// 'menubar/add/mesh/icosahedron': 'Icosahedron',
			'menubar/add/mesh/octahedron': 'Octahedron',
			// 'menubar/add/mesh/tetrahedron': 'Tetrahedron',
			// 'menubar/add/mesh/torus': 'Torus',
			// 'menubar/add/mesh/tube': 'Tube',
			// 'menubar/add/mesh/torusknot': 'TorusKnot',
			// 'menubar/add/mesh/lathe': 'Lathe',
			// 'menubar/add/mesh/sprite': 'Sprite',
			//'menubar/add/monkey': 'Monkey',
			'menubar/add/cone': 'Cone',
			'menubar/add/spawn': 'Spawn',
			//'menubar/add/monkey': 'Monkey',

			'menubar/add/light': 'Light',
			'menubar/add/light/ambient': 'Ambient',
			'menubar/add/light/directional': 'Directional',
			'menubar/add/light/hemisphere': 'Hemisphere',
			'menubar/add/light/point': 'Point',
			'menubar/add/light/spot': 'Spot',

			'menubar/add/camera': 'Camera',
			'menubar/add/camera/perspective': 'Perspective',
			'menubar/add/camera/orthographic': 'Orthographic',

			'menubar/status/autosave': 'autosave',

			'menubar/view': 'View',
			'menubar/view/fullscreen': 'Fullscreen',
			'menubar/view/gridHelper': 'Grid',
			'menubar/view/cameraHelpers': 'Camera Helpers',
			'menubar/view/lightHelpers': 'Light Helpers',
			'menubar/view/skeletonHelpers': 'Skeleton Helpers',

			'menubar/help': 'Help',
			'menubar/help/source_code': 'Source Code',
			'menubar/help/icons': 'Icon Pack',
			'menubar/help/about': 'About',
			'menubar/help/manual': 'Manual',

			'sidebar/animations': 'Animations',
			'sidebar/animations/play': 'Play',
			'sidebar/animations/stop': 'Stop',
			'sidebar/animations/timescale': 'Time Scale',

			'sidebar/scene': 'Scene',
			'sidebar/scene/background': 'Background',
			'sidebar/scene/environment': 'Environment',
			'sidebar/scene/fog': 'Fog',

			'sidebar/properties/object': 'Object',
			'sidebar/properties/geometry': 'Geometry',
			'sidebar/properties/material': 'Material',
			'sidebar/properties/script': 'Script',
			'sidebar/properties/effects': 'Effects',

			'sidebar/object/type': 'Type',
			'sidebar/object/new': 'New',
			'sidebar/object/uuid': 'UUID',
			'sidebar/object/name': 'Name',
			'sidebar/object/position': 'Position',
			'sidebar/object/rotation': 'Rotation',
			'sidebar/object/scale': 'Scale',
			'sidebar/object/fov': 'Fov',
			'sidebar/object/left': 'Left',
			'sidebar/object/right': 'Right',
			'sidebar/object/top': 'Top',
			'sidebar/object/bottom': 'Bottom',
			'sidebar/object/near': 'Near',
			'sidebar/object/far': 'Far',
			'sidebar/object/intensity': 'Intensity',
			'sidebar/object/color': 'Color',
			'sidebar/object/groundcolor': 'Ground Color',
			'sidebar/object/distance': 'Distance',
			'sidebar/object/angle': 'Angle',
			'sidebar/object/penumbra': 'Penumbra',
			'sidebar/object/decay': 'Decay',
			'sidebar/object/shadow': 'Shadow',
			'sidebar/object/shadowIntensity': 'Shadow Intensity',
			'sidebar/object/shadowBias': 'Shadow Bias',
			'sidebar/object/shadowNormalBias': 'Shadow Normal Bias',
			'sidebar/object/shadowRadius': 'Shadow Radius',
			'sidebar/object/cast': 'cast',
			'sidebar/object/receive': 'receive',
			'sidebar/object/visible': 'Visible',
			'sidebar/object/frustumcull': 'Frustum Cull',
			'sidebar/object/renderorder': 'Render Order',
			'sidebar/object/userdata': 'User data',
			'sidebar/object/export': 'Export JSON',

			'sidebar/effects/use': 'use',
			'sidebar/effects/drift': 'drift',
			'sidebar/effects/jump': 'jump',
			'sidebar/effects/jh': 'jh',
			'sidebar/effects/js': 'js',
			'sidebar/effects/turn': 'turn',
			'sidebar/effects/speed': 'speed',
			'sidebar/effects/dx': 'dx',
			'sidebar/effects/dy': 'dy',
			'sidebar/effects/dz': 'dz',
			'sidebar/effects/sl': 'sl',
			'sidebar/effects/sr': 'sr',
			'sidebar/effects/id': 'id',
			'sidebar/effects/mx': 'mx',
			'sidebar/effects/my': 'my',
			'sidebar/effects/mz': 'mz',
			'sidebar/effects/rx': 'rx',
			'sidebar/effects/ry': 'ry',
			'sidebar/effects/rz': 'rz',
			'sidebar/effects/gx': 'gx',
			'sidebar/effects/gy': 'gy',
			'sidebar/effects/gz': 'gz',
			'sidebar/effects/bou': 'bou',
			'sidebar/effects/mass': 'mass',
			'sidebar/effects/fr': 'fr',
			'sidebar/effects/air': 'air',
			'sidebar/effects/topr': 'topr',
			'sidebar/effects/k': 'k',
			'sidebar/effects/d': 'd',
			'sidebar/effects/eye': 'eye',
			'sidebar/effects/fov': 'fov',
			'sidebar/effects/tx': 'tx',
			'sidebar/effects/ty': 'ty',
			'sidebar/effects/tz': 'tz',
			'sidebar/effects/cd': 'cd',
			'sidebar/effects/cr': 'cr',
			'sidebar/effects/msg': 'msg',
			'sidebar/effects/br': 'br',
			'sidebar/effects/bg': 'bg',
			'sidebar/effects/amb': 'amb',
			'sidebar/effects/dif': 'dif',
			'sidebar/effects/spe': 'spe',
			'sidebar/effects/gro': 'gro',

			'sidebar/geometry/type': 'Type',
			'sidebar/geometry/new': 'New',
			'sidebar/geometry/uuid': 'UUID',
			'sidebar/geometry/name': 'Name',
			'sidebar/geometry/bounds': 'Bounds',
			'sidebar/geometry/userdata': 'User Data',
			'sidebar/geometry/show_vertex_normals': 'Show Vertex Normals',
			'sidebar/geometry/compute_vertex_normals': 'Compute Vertex Normals',
			'sidebar/geometry/compute_vertex_tangents': 'Compute Tangents',
			'sidebar/geometry/center': 'Center',
			'sidebar/geometry/export': 'Export JSON',

			'sidebar/geometry/box_geometry/width': 'Width',
			'sidebar/geometry/box_geometry/height': 'Height',
			'sidebar/geometry/box_geometry/depth': 'Depth',
			'sidebar/geometry/box_geometry/widthseg': 'Width Seg',
			'sidebar/geometry/box_geometry/heightseg': 'Height Seg',
			'sidebar/geometry/box_geometry/depthseg': 'Depth Seg',

			'sidebar/geometry/cone_geometry/radius': 'Radius',
			'sidebar/geometry/cone_geometry/height': 'Height',
			'sidebar/geometry/cone_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/cone_geometry/heightsegments': 'Height segments',
			'sidebar/geometry/cone_geometry/openended': 'Open ended',

			'sidebar/geometry/buffer_geometry/attributes': 'Attributes',
			'sidebar/geometry/buffer_geometry/index': 'index',
			'sidebar/geometry/buffer_geometry/morphAttributes': 'Morph Attributes',
			'sidebar/geometry/buffer_geometry/morphRelative': 'Morph Relative',

			'sidebar/geometry/capsule_geometry/radius': 'Radius',
			'sidebar/geometry/capsule_geometry/length': 'Length',
			'sidebar/geometry/capsule_geometry/capseg': 'Cap Seg',
			'sidebar/geometry/capsule_geometry/radialseg': 'Radial Seg',

			'sidebar/geometry/circle_geometry/radius': 'Radius',
			'sidebar/geometry/circle_geometry/segments': 'Segments',
			'sidebar/geometry/circle_geometry/thetastart': 'Theta start',
			'sidebar/geometry/circle_geometry/thetalength': 'Theta length',

			'sidebar/geometry/cylinder_geometry/radiustop': 'Radius top',
			'sidebar/geometry/cylinder_geometry/radiusbottom': 'Radius bottom',
			'sidebar/geometry/cylinder_geometry/height': 'Height',
			'sidebar/geometry/cylinder_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/cylinder_geometry/heightsegments': 'Height segments',
			'sidebar/geometry/cylinder_geometry/openended': 'Open ended',

			'sidebar/geometry/extrude_geometry/curveSegments': 'Curve Segments',
			'sidebar/geometry/extrude_geometry/steps': 'Steps',
			'sidebar/geometry/extrude_geometry/depth': 'Depth',
			'sidebar/geometry/extrude_geometry/bevelEnabled': 'Bevel',
			'sidebar/geometry/extrude_geometry/bevelThickness': 'Thickness',
			'sidebar/geometry/extrude_geometry/bevelSize': 'Size',
			'sidebar/geometry/extrude_geometry/bevelOffset': 'Offset',
			'sidebar/geometry/extrude_geometry/bevelSegments': 'Segments',
			'sidebar/geometry/extrude_geometry/shape': 'Convert to Shape',

			'sidebar/geometry/dodecahedron_geometry/radius': 'Radius',
			'sidebar/geometry/dodecahedron_geometry/detail': 'Detail',

			'sidebar/geometry/icosahedron_geometry/radius': 'Radius',
			'sidebar/geometry/icosahedron_geometry/detail': 'Detail',

			'sidebar/geometry/octahedron_geometry/radius': 'Radius',
			'sidebar/geometry/octahedron_geometry/detail': 'Detail',

			'sidebar/geometry/tetrahedron_geometry/radius': 'Radius',
			'sidebar/geometry/tetrahedron_geometry/detail': 'Detail',

			'sidebar/geometry/lathe_geometry/segments': 'Segments',
			'sidebar/geometry/lathe_geometry/phistart': 'Phi start (°)',
			'sidebar/geometry/lathe_geometry/philength': 'Phi length (°)',
			'sidebar/geometry/lathe_geometry/points': 'Points',

			'sidebar/geometry/plane_geometry/width': 'Width',
			'sidebar/geometry/plane_geometry/height': 'Height',
			'sidebar/geometry/plane_geometry/widthsegments': 'Width segments',
			'sidebar/geometry/plane_geometry/heightsegments': 'Height segments',

			'sidebar/geometry/ring_geometry/innerRadius': 'Inner radius',
			'sidebar/geometry/ring_geometry/outerRadius': 'Outer radius',
			'sidebar/geometry/ring_geometry/thetaSegments': 'Theta segments',
			'sidebar/geometry/ring_geometry/phiSegments': 'Phi segments',
			'sidebar/geometry/ring_geometry/thetastart': 'Theta start',
			'sidebar/geometry/ring_geometry/thetalength': 'Theta length',

			'sidebar/geometry/shape_geometry/curveSegments': 'Curve Segments',
			'sidebar/geometry/shape_geometry/extrude': 'Extrude',

			'sidebar/geometry/sphere_geometry/radius': 'Radius',
			'sidebar/geometry/sphere_geometry/widthsegments': 'Width segments',
			'sidebar/geometry/sphere_geometry/heightsegments': 'Height segments',
			'sidebar/geometry/sphere_geometry/phistart': 'Phi start',
			'sidebar/geometry/sphere_geometry/philength': 'Phi length',
			'sidebar/geometry/sphere_geometry/thetastart': 'Theta start',
			'sidebar/geometry/sphere_geometry/thetalength': 'Theta length',

			'sidebar/geometry/torus_geometry/radius': 'Radius',
			'sidebar/geometry/torus_geometry/tube': 'Tube',
			'sidebar/geometry/torus_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/torus_geometry/tubularsegments': 'Tubular segments',
			'sidebar/geometry/torus_geometry/arc': 'Arc',

			'sidebar/geometry/torusKnot_geometry/radius': 'Radius',
			'sidebar/geometry/torusKnot_geometry/tube': 'Tube',
			'sidebar/geometry/torusKnot_geometry/tubularsegments': 'Tubular segments',
			'sidebar/geometry/torusKnot_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/torusKnot_geometry/p': 'P',
			'sidebar/geometry/torusKnot_geometry/q': 'Q',

			'sidebar/geometry/tube_geometry/path': 'Path',
			'sidebar/geometry/tube_geometry/radius': 'Radius',
			'sidebar/geometry/tube_geometry/tube': 'Tube',
			'sidebar/geometry/tube_geometry/tubularsegments': 'Tubular segments',
			'sidebar/geometry/tube_geometry/radialsegments': 'Radial segments',
			'sidebar/geometry/tube_geometry/closed': 'Closed',
			'sidebar/geometry/tube_geometry/curvetype': 'Curve Type',
			'sidebar/geometry/tube_geometry/tension': 'Tension',

			'sidebar/material/new': 'New',
			'sidebar/material/copy': 'Copy',
			'sidebar/material/paste': 'Paste',
			'sidebar/material/slot': 'Slot',
			'sidebar/material/type': 'Type',
			'sidebar/material/uuid': 'UUID',
			'sidebar/material/name': 'Name',
			'sidebar/material/program': 'Program',
			'sidebar/material/info': 'Info',
			'sidebar/material/vertex': 'Vert',
			'sidebar/material/fragment': 'Frag',
			'sidebar/material/color': 'Color',
			'sidebar/material/depthPacking': 'Depth Packing',
			'sidebar/material/roughness': 'Roughness',
			'sidebar/material/metalness': 'Metalness',
			'sidebar/material/reflectivity': 'Reflectivity',
			'sidebar/material/emissive': 'Emissive',
			'sidebar/material/specular': 'Specular',
			'sidebar/material/shininess': 'Shininess',
			'sidebar/material/clearcoat': 'Clearcoat',
			'sidebar/material/clearcoatroughness': 'Clearcoat Roughness',
			'sidebar/material/dispersion': 'Dispersion',
			'sidebar/material/ior': 'IOR',
			'sidebar/material/iridescence': 'Iridescence',
			'sidebar/material/iridescenceIOR': 'Thin-Film IOR',
			'sidebar/material/iridescenceThicknessMax': 'Thin-Film Thickness',
			'sidebar/material/sheen': 'Sheen',
			'sidebar/material/sheenroughness': 'Sheen Roughness',
			'sidebar/material/sheencolor': 'Sheen Color',
			'sidebar/material/transmission': 'Transmission',
			'sidebar/material/attenuationDistance': 'Attenuation Distance',
			'sidebar/material/attenuationColor': 'Attenuation Color',
			'sidebar/material/thickness': 'Thickness',
			'sidebar/material/vertexcolors': 'Vertex Colors',
			'sidebar/material/matcap': 'Matcap',
			'sidebar/material/map': 'Map',
			'sidebar/material/alphamap': 'Alpha Map',
			'sidebar/material/bumpmap': 'Bump Map',
			'sidebar/material/normalmap': 'Normal Map',
			'sidebar/material/clearcoatmap': 'Clearcoat Map',
			'sidebar/material/clearcoatnormalmap': 'Clearcoat Normal Map',
			'sidebar/material/clearcoatroughnessmap': 'Clearcoat Roughness Map',
			'sidebar/material/displacementmap': 'Displace Map',
			'sidebar/material/roughnessmap': 'Rough. Map',
			'sidebar/material/metalnessmap': 'Metal. Map',
			'sidebar/material/specularmap': 'Specular Map',
			'sidebar/material/iridescencemap': 'Irid. Map',
			'sidebar/material/iridescencethicknessmap': 'Thin-Film Thickness Map',
			'sidebar/material/sheencolormap': 'Sheen Color Map',
			'sidebar/material/sheenroughnessmap': 'Sheen Rough. Map',
			'sidebar/material/envmap': 'Env Map',
			'sidebar/material/lightmap': 'Light Map',
			'sidebar/material/aomap': 'AO Map',
			'sidebar/material/emissivemap': 'Emissive Map',
			'sidebar/material/gradientmap': 'Gradient Map',
			'sidebar/material/transmissionmap': 'Transmission Map',
			'sidebar/material/thicknessmap': 'Thickness Map',
			'sidebar/material/side': 'Side',
			'sidebar/material/size': 'Size',
			'sidebar/material/sizeAttenuation': 'Size Attenuation',
			'sidebar/material/flatShading': 'Flat Shading',
			'sidebar/material/blending': 'Blending',
			'sidebar/material/opacity': 'Opacity',
			'sidebar/material/transparent': 'Transparent',
			'sidebar/material/forcesinglepass': 'Force Single Pass',
			'sidebar/material/alphatest': 'Alpha Test',
			'sidebar/material/depthtest': 'Depth Test',
			'sidebar/material/depthwrite': 'Depth Write',
			'sidebar/material/wireframe': 'Wireframe',
			'sidebar/material/userdata': 'User data',
			'sidebar/material/export': 'Export JSON',

			'sidebar/script/new': 'New',
			'sidebar/script/edit': 'Edit',
			'sidebar/script/remove': 'Remove',

			'sidebar/project': 'Monkey',
			'sidebar/project/antialias': 'Antialias',
			'sidebar/project/shadows': 'Shadows',
			'sidebar/project/toneMapping': 'Tonemapping',
			'sidebar/project/materials': 'Materials',
			'sidebar/project/Assign': 'Assign',

			'sidebar/project/app': 'App',
			'sidebar/project/app/play': 'Play',
			'sidebar/project/app/stop': 'Stop',
			'sidebar/project/app/title': 'Title',
			'sidebar/project/app/editable': 'Editable',
			'sidebar/project/app/publish': 'Publish',
			'sidebar/project/app/url': 'Get URL',
			'sidebar/project/app/loadurl': 'Load URL (early alpha)',

			'sidebar/project/image': 'Image',
			'sidebar/project/image/samples': 'Samples',
			'sidebar/project/video': 'Video',

			'sidebar/project/shading': 'Shading',
			'sidebar/project/resolution': 'Resolution',
			'sidebar/project/duration': 'Duration',
			'sidebar/project/render': 'Render',

			'sidebar/settings': 'Settings',
			'sidebar/settings/language': 'Language',

			'sidebar/settings/shortcuts': 'Shortcuts',
			'sidebar/settings/shortcuts/translate': 'Translate',
			'sidebar/settings/shortcuts/rotate': 'Rotate',
			'sidebar/settings/shortcuts/scale': 'Scale',
			'sidebar/settings/shortcuts/undo': 'Undo',
			'sidebar/settings/shortcuts/focus': 'Focus',

			'sidebar/history': 'History',
			'sidebar/history/clear': 'Clear',
			'sidebar/history/persistent': 'Persistent',

			'toolbar/translate': 'Translate',
			'toolbar/rotate': 'Rotate',
			'toolbar/scale': 'Scale',
			'toolbar/local': 'Local',

			'viewport/controls/grid': 'Grid',
			'viewport/controls/helpers': 'Helpers',

			'viewport/info/object': 'Object',
			'viewport/info/objects': 'Objects',
			'viewport/info/vertex': 'Vertex',
			'viewport/info/vertices': 'Vertices',
			'viewport/info/triangle': 'Triangle',
			'viewport/info/triangles': 'Triangles',
			'viewport/info/sample': 'Sample',
			'viewport/info/samples': 'Samples',
			'viewport/info/rendertime': 'Render time',

			'script/title/vertexShader': 'Vertex Shader',
			'script/title/fragmentShader': 'Fragment Shader',
			'script/title/programInfo': 'Program Properties'

		},

	};

	return {

		getKey: function ( key ) {

			return values[ language ][ key ] || '???';

		}

	};

}

export { Strings };
